### PR TITLE
refactor of StreamHandler and EventStore client

### PR DESCRIPTION
**Pull request by rhofland**
This pull request is to fix an issue when a data stream contains multiple complete messages. The handle method will now return an array of SocketMessages instead of just 1. The EventStore client has also been changed to handle the multiple messages. 

If the last part of the data stream contain a partial message, this will be kept in the instance variable as before. 

A test has been added to test this new scenario and previous test have been updated to expect the array of socketMessages.

### CODE REVIEW

**Comment by rhofland** [comment]
btw, I noticed this when I updated a persistent subscription through the GetEventStore UI. This automatically disconnects any clients running. When I restarted the client it would disconnect after a few seconds. Turns out 2 complete message are being pushed upon re-connect and the code wasn't handling it right. @JurJean : This might also explain the inflight messages not working as they might appear as multiple complete messages in the stream.

**Comment by dgafka** [comment]
Hey, thanks for active contribution. I will check your MR today's evening or tommorow's morning.
I haven't seen this multi-message socket before. So I am glad you found it out :)

**Comment by JurJean** [comment]
Awesome!

**Comment by dgafka** [comment]
Merged.
I also have added docker-compose for usage examples / testing purposes. 
Docker-compose contains eventstore in 3.4.0 version and php+protobuf installed.

It is published as 0.9.5 version now.

**Pull request merged**
